language: node_js
node_js:
- node
- 8
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: wsZnK4wBDvQRJ8WK4Mei/foEAmy1+aWAT1QJd5BmheApVkUom44iH5xmA0/1sfJj/7HvZYAPczOiWkkifETDplfaYDt+kPY0TSMsPALBQbj6lRbR4UnlsUXVZn0fW2OefKN5tCEXlAnBe5D7Pfv8oWwa6t9jwCon571nNzUjWHCDt0O/5eCvnfnuQX5eDQPFKcBtdr1J2TYRT791JzJDn1KGXaioJnxknsYts2rrWbfDJeKjgT3GaEt91VixN52W1Hhuv+NJE+rnZbYAsB+avFpHzD1SMWeZfjVAFY43JZPagkm+PXJY/dLrwZ+1yVhrL96iWKEJF3DCk/MhUXck9eQu9okIcIk2TZq1KQAg4l9jxiJ6MOFVYvghHZjVeblKn/QhDc2uiFhW+XfpzpA+dwVMx5TYhbt8bFBl0W830vM8jyjAk88EFUjyRT0gVCS3Dvx2P42zyPUECTpYDoTC/DFZ4el7ijzxoRppJFqLTip/nDNvzLOBGuKpefQydr/CoA6kgQrBMPQngh4/YxDvqp58i9hJmxrYfqIvxUVSUxn0KNDYojD5TLldV3W4k1PG2PvTxfK0uJ03lmVP/hRYZma4eSzkM7/Dc7Jt76CzXENcFb4jPG/pZZ5NdNLlToQeRMnqqtI210/V/idijSrIY36eHoPHrktrEx1h6JdmKOs=
  on:
    tags: true
    repo: xogroup/origami-logs
