language: node_js
node_js:
- node
- 8
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: wRZrv68UaEd1gi8GTZymlCRzEsxSAqz2fa+lfyhL474qm9wqBDElRMA2vsmGL//DJT3XasDAtvgFuuBzTzgwEcfp7xyZwXOb5QxCoQOl5/ohIbba0A9NulsQWsA6T23iX5d3Kor488PH9RARoqMArWMEJwCy/UCbiDDGrv1GLdaf7wWUkPd8lbcNbdgHQr+5FlyyVgIXq6F8KB3DT/NFtP7Ma5d5vyIkKxjTeyca30D7vQAhanusYzL6fTw4JrD7rHcLMCO6qm73oKYyUdvQiVNtKA/Nb8ayUIDepHAYkig2+xBvjTHHMLwVyaOH+xv38Jx7XLUBOEDJFyYhjJsiKKDEZ+MU9yzrXFmpBobV3jbNF9To/tV8HEYvincby8D6tGkmSU40+8mcblvmympHTCqBBaFvI6foi3rqpeASBiXn8HB0PagUY+sGt+D53AoNWFbLEJVfOqPvAt4vGOK2OqRB2AN3CusJATkMh8VHFKBhZj6uAOhdQmY9uI6vMu5DVBbntahXk1pXaX0gJwnDXp5FOSmucG4SuRVLeEbN17z0W1u6/E7MyGysIDPnFhfG5Gn7fuLGu26S28Z/tyRDJp4CimkSjAKVkCdd07/jSNrio36Rd/zIiC8qZfFj1rA6Ate9lgl9wZsFmJVayeXc+Zsx9xFJGo5W8f4D+jhT30s=
  on:
    tags: true
    repo: xogroup/changelogger
